spring:
  application:
    name: insta-auth

  data:
    mongodb:
      uri: mongodb+srv://mygcp98:ZrOGQlVsHJTqGXHA@cluster0.8aqqmhb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: Cluster0

  cloud:
    stream:
      kafka:
        binder:
          brokers: 34.16.154.69:9092
          configuration:
              key:
                serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        momentsUserChanged:
          destination: moments.user.changed
          contentType: application/json
server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: https://verbose-fishstick-grprr7699qv3w7p4-8761.app.github.dev/eureka
      
security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33